---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: filexplorer
spec:
  rules:
    - host: services-dev.com
      http:
        paths:
          - path: /api/filexplorer/v1
            backend:
              serviceName: filexplorer
              servicePort: 80
