---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: filexplorer
  annotations:
    kubernetes.io/description: PSP for filexplorer
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: true

  allowedCapabilities: [ SETUID, SETGID ]
  requiredDropCapabilities: [ ]
  defaultAddCapabilities: [ ]

  hostNetwork: false
  hostIPC: false
  hostPID: false

  seLinux: # harness for SELinux
    rule: RunAsAny

  runAsUser:
    rule: MustRunAsNonRoot
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 65535
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 65535
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 65535
  volumes:
    - configMap
    - secret
    - emptyDir
    - persistentVolumeClaim
  readOnlyRootFilesystem: false