---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: filexplorer
rules:
  - apiGroups: [ policy ]
    resources: [ podsecuritypolicies ]
    verbs: [ use ]
    resourceNames: [ filexplorer ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: filexplorer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: filexplorer
subjects:
  - kind: ServiceAccount
    name: filexplorer